---
# Setting up all hosts
- hosts: proxy:masters:workers
  tasks: [ ]

# Proxy has public ip
- hosts: proxy
  roles:
    - iptables

# this force reload iptables
- hosts: proxy
  tasks:
    - meta: flush_handlers

- hosts: proxy
  roles:
    - tinyproxy

# this force reload tinyproxy
- hosts: proxy
  tasks:
    - meta: flush_handlers

# Setting up apt-proxy on master and workers (private ips)
- hosts: masters:workers
  roles:
    - apt-proxy

# Masters and workers have private ips
- hosts: proxy:masters:workers
  roles:
    - common
    - docker
