- name: Get volume infos
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info

- name: Create Gluster volume
  shell: "{{ lookup('template', 'templates/gluster_brick_config.j2') }}"
  register: gluster_volume_create
  changed_when: "'successful' in gluster_volume_create.stdout"
  when: "inventory_hostname == groups.gluster[0] and 'Volume Name: gvol_{{ item }}' not in gluster_volume_info.stdout"
  with_items:
    - "{{ groups.gluster[0] }}"

- name: Ensure Gluster volume is started.
  shell: "gluster volume start gvol_{{ item }}"
  register: gluster_volume_start
  changed_when: "'successful' in gluster_volume_start.stdout"
  when: "inventory_hostname == groups.gluster[0] and 'Volume Name: gvol_{{ item }}' not in gluster_volume_info.stdout"
  with_items:
    - "{{ groups.gluster[0] }}"
