- name: Creating bricks mountpoint
  file:
    path: "/data/k8s/{{ item }}"
    state: directory
  with_items:
  - "{{ groups.gluster[0] }}"

- name: Mounting bricks
  mount:
    name: "/data/k8s/{{ item }}"
    src: "{{ groups.gluster[0] }}:gvol_{{ item }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
  with_items:
  - "{{ groups.gluster[0] }}"
