- name: Squid for Ubuntu server
  block:

  - name: Install squid on the proxy server
    apt:
      name: squid3
      state: latest

  - name: Ensure squid is stopped
    systemd:
      name: squid
      state: stopped

  - name: Templating /etc/squid/squid.conf
    template:
      src: squid.conf.j2
      dest: /etc/squid/squid.conf

  - name: Ensure squid is started
    systemd:
      name: squid
      state: started
      enabled: yes

  when: ansible_distribution == "Ubuntu"
